//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppPersonas.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/appPersonas")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PersonsDetails", Namespace="http://schemas.datacontract.org/2004/07/appPersonas")]
    [System.SerializableAttribute()]
    public partial class PersonsDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoPersonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoPersonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionPersonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdentidadPersonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime NacimientoPersonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombrePersonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoPersonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoDireccionPersonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoTelefonoPersonField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApellidoPerson {
            get {
                return this.ApellidoPersonField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoPersonField, value) != true)) {
                    this.ApellidoPersonField = value;
                    this.RaisePropertyChanged("ApellidoPerson");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CorreoPerson {
            get {
                return this.CorreoPersonField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoPersonField, value) != true)) {
                    this.CorreoPersonField = value;
                    this.RaisePropertyChanged("CorreoPerson");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DireccionPerson {
            get {
                return this.DireccionPersonField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionPersonField, value) != true)) {
                    this.DireccionPersonField = value;
                    this.RaisePropertyChanged("DireccionPerson");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdentidadPerson {
            get {
                return this.IdentidadPersonField;
            }
            set {
                if ((object.ReferenceEquals(this.IdentidadPersonField, value) != true)) {
                    this.IdentidadPersonField = value;
                    this.RaisePropertyChanged("IdentidadPerson");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime NacimientoPerson {
            get {
                return this.NacimientoPersonField;
            }
            set {
                if ((this.NacimientoPersonField.Equals(value) != true)) {
                    this.NacimientoPersonField = value;
                    this.RaisePropertyChanged("NacimientoPerson");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombrePerson {
            get {
                return this.NombrePersonField;
            }
            set {
                if ((object.ReferenceEquals(this.NombrePersonField, value) != true)) {
                    this.NombrePersonField = value;
                    this.RaisePropertyChanged("NombrePerson");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TelefonoPerson {
            get {
                return this.TelefonoPersonField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoPersonField, value) != true)) {
                    this.TelefonoPersonField = value;
                    this.RaisePropertyChanged("TelefonoPerson");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoDireccionPerson {
            get {
                return this.TipoDireccionPersonField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoDireccionPersonField, value) != true)) {
                    this.TipoDireccionPersonField = value;
                    this.RaisePropertyChanged("TipoDireccionPerson");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoTelefonoPerson {
            get {
                return this.TipoTelefonoPersonField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoTelefonoPersonField, value) != true)) {
                    this.TipoTelefonoPersonField = value;
                    this.RaisePropertyChanged("TipoTelefonoPerson");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        WebAppPersonas.ServiceReference1.CompositeType GetDataUsingDataContract(WebAppPersonas.ServiceReference1.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<WebAppPersonas.ServiceReference1.CompositeType> GetDataUsingDataContractAsync(WebAppPersonas.ServiceReference1.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPersonRecords", ReplyAction="http://tempuri.org/IService1/GetPersonRecordsResponse")]
        System.Data.DataSet GetPersonRecords();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPersonRecords", ReplyAction="http://tempuri.org/IService1/GetPersonRecordsResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetPersonRecordsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertPersondetails", ReplyAction="http://tempuri.org/IService1/InsertPersondetailsResponse")]
        string InsertPersondetails(WebAppPersonas.ServiceReference1.PersonsDetails persons);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertPersondetails", ReplyAction="http://tempuri.org/IService1/InsertPersondetailsResponse")]
        System.Threading.Tasks.Task<string> InsertPersondetailsAsync(WebAppPersonas.ServiceReference1.PersonsDetails persons);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WebAppPersonas.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WebAppPersonas.ServiceReference1.IService1>, WebAppPersonas.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public WebAppPersonas.ServiceReference1.CompositeType GetDataUsingDataContract(WebAppPersonas.ServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<WebAppPersonas.ServiceReference1.CompositeType> GetDataUsingDataContractAsync(WebAppPersonas.ServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public System.Data.DataSet GetPersonRecords() {
            return base.Channel.GetPersonRecords();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetPersonRecordsAsync() {
            return base.Channel.GetPersonRecordsAsync();
        }
        
        public string InsertPersondetails(WebAppPersonas.ServiceReference1.PersonsDetails persons) {
            return base.Channel.InsertPersondetails(persons);
        }
        
        public System.Threading.Tasks.Task<string> InsertPersondetailsAsync(WebAppPersonas.ServiceReference1.PersonsDetails persons) {
            return base.Channel.InsertPersondetailsAsync(persons);
        }
    }
}
